"""updated

Revision ID: 7107cbe9ba5a
Revises: cbc5e4165efc
Create Date: 2024-04-19 12:04:21.815937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7107cbe9ba5a'
down_revision = 'cbc5e4165efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
