"""updated

Revision ID: 9971c2abcb4e
Revises: 7107cbe9ba5a
Create Date: 2024-04-19 12:31:12.945989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9971c2abcb4e'
down_revision = '7107cbe9ba5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
